### ISSUE TITLE
SDRemix Bowser down throw crashes

### ISSUE THREAD

**Issue by Dean777233** [DRGN-DRC/20XX-HACK-PACK#2]
Only tested with Jigglypuff and Fox on Pokémon stadium, dunno if it's with all characters, but regardless, it crashes the game.

**Comment by DRGN-DRC** [comment]
Thanks. This will be fixed in the next version of SD Remix.

**Comment by DRGN-DRC** [comment]
I forgot to come back here and close this, but this bug was fixed in 20XX v5.0.1 (SDR v5.1).
